### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by andresriancho** [kai3n/Orroid#1]
What am I doing wrong? Here I'm pointing orroid to the source folder, an error appears:

``` console
[pablo:/home/pablo/tools/Orroid] master ± ruby orroid.rb -s -E /home/pablo/mPos/src/
Project Name : /home/pablo/mPos/src/

secure/secure_coding.rb:125:in `sec_cod_run': undefined method `package' for nil:NilClass (NoMethodError)
    from orroid.rb:24:in `<main>'
[pablo:/home/pablo/tools/Orroid] master 1 ±
```

Then I point it to the apk:

``` console
[pablo:/home/pablo/tools/Orroid] master 1 ± ruby orroid.rb -s -E /home/pablo/mPos/apk/mPos.apk 
Project Name : /home/pablo/mPos/apk/mPos.apk

secure/secure_coding.rb:125:in `sec_cod_run': undefined method `package' for nil:NilClass (NoMethodError)
    from orroid.rb:24:in `<main>'
[pablo:/home/pablo/tools/Orroid] master 1 ±
```

Same error appears, so I guess I have to create a project? But that doesn't work either:

``` console
[pablo:/home/pablo/tools/Orroid] master ± ruby orroid.rb -p project
/usr/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - decompiling\lib_orroid.jar (Errno::ENOENT)
    from /usr/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
    from /usr/lib/ruby/1.9.1/fileutils.rb:395:in `cp'
    from decompiling/put_lib.rb:10:in `project_run'
    from orroid.rb:26:in `<main>'
```

Ruby version:

``` console
[pablo:/home/pablo/tools/Orroid] master 130 ± ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
[pablo:/home/pablo/tools/Orroid] master ± 
```

I liked the tool concept and the ~100 signatures to detect bugs, but I don't seem to be able to run it (and don't have time now to read the source)-

**Comment by kai3n** [comment]
Sorry for response late, I've seen your question now....
Um.. I think that is working on ruby 1.6.\* version?
Try it again, if you have any question more, feel free to ask me.
Have a nice day!:)

2015-04-08 21:37 GMT+09:00 Andres Riancho notifications@github.com:
